import { chromium } from 'playwright';
const SC='/tmp/claude-0/-home-user-May-madness/0e44f0ad-a683-5f0d-9de6-9459ae328963/scratchpad';
const name = process.argv[2] || 'capture-poster';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const p=await b.newPage({viewport:{width:1080,height:1528},deviceScaleFactor:3});
await p.goto('file://'+SC+'/'+name+'.html',{waitUntil:'load'});
await p.waitForTimeout(1200);
console.log(await p.evaluate(()=>{const z=document.querySelector('.z');
  const l=z.lastElementChild;
  return 'content bottom '+Math.round(l.getBoundingClientRect().bottom)+' of '+innerHeight;}));
await p.screenshot({path:SC+'/'+name+'@3x.png'});
await b.close();
