# -*- coding: utf-8 -*-
"""Generate ops/sync-aa-to-surge.js — carries August Attack into September Surge.

Only the ALL-TIME total carries: each player's final Vol.6 points are written
into September Surge as prevSeriesPts["August Attack"], which the app sums into
the all-time ranking. The Vol.7 series table itself starts empty and is
untouched by this script.

Modelled on the July Heat -> August Attack sync that already ran for the
previous volume, with the scoring engine lifted verbatim out of
august-attack-index.html so the totals equal what attack.urbanpadel.om shows —
not a re-implementation that could drift.

Idempotent: safe to run now for a preview of the roster, and again the moment
Session 9's knockouts finish, which is when the numbers become final.

  python3 ops/build-surge-carryover.py
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "august-attack-index.html")
OUT = os.path.join(HERE, "sync-aa-to-surge.js")

NEEDED = ["getPlayerTeam", "teamWon", "teamGroupResults", "calcGroupStandings", "getTopOfGroup",
          "calcStreak", "koMatchPts", "calcPlayerStats"]


def grab(html, name):
    i = html.index(f"function {name}(")
    j = html.index("{", i)
    depth, k = 0, j
    while True:
        if html[k] == "{":
            depth += 1
        elif html[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    return html[i:k + 1]


def main():
    html = open(SRC).read()
    m = re.search(r"const GROUP_COUNTED_GAMES\s*=\s*\d+;", html)
    if not m:
        sys.exit("BUILD FAILED: GROUP_COUNTED_GAMES not found")
    engine = [m.group(0)] + [grab(html, n) for n in NEEDED]

    js = '''// GENERATED by ops/build-surge-carryover.py — do not edit by hand.
//
// Carries August Attack (Vol.6) into September Surge (Vol.7) as ALL-TIME only:
// each player's final Vol.6 total lands in prevSeriesPts["August Attack"], which
// the app adds to the all-time ranking. The Vol.7 series table starts at zero
// and is never written here — no sessions, no matches, no series points.
//
// The scoring functions below are lifted verbatim from august-attack-index.html,
// so totals match attack.urbanpadel.om exactly, including the best-3 group cap,
// 2x sessions, knockout points, streak and comeback bonuses.
//
// Idempotent. Reads August Attack, writes only September Surge.
// DRY=1 previews without writing.
require("dotenv").config({ path: "/opt/september-surge-api/.env" });
const { Pool } = require("pg");
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const DRY = process.env.DRY === "1";
const SERIES = "August Attack";
const GROUPS = ["A", "B", "C", "D"];
function getSessionGroups(session) { return GROUPS.slice(0, session?.groupCount || 4); }

''' + "\n\n".join(engine) + '''

(async () => {
  const aa = (await pool.query("select data from aa_tournament_state where id=1")).rows[0]?.data;
  const ssRow = (await pool.query("select data, version from ss_tournament_state where id=1")).rows[0];
  if (!aa) throw new Error("missing aa_tournament_state");
  if (!ssRow) throw new Error("missing ss_tournament_state — is september-surge-api running?");

  const ss = ssRow.data && Object.keys(ssRow.data).length ? ssRow.data : {};
  ss.players = ss.players || [];
  ss.sessions = ss.sessions || [];

  const sessionsBefore = ss.sessions.length;
  const sessions = aa.sessions || [];
  const unfinished = sessions.filter(s => !s.completed).map(s => s.name);
  if (unfinished.length)
    console.log("NOTE: Vol.6 still has unfinished sessions:", unfinished.join(", "),
                "\\n      totals are provisional — re-run this after they complete.\\n");

  // Final Vol.6 totals, straight from the app's own engine.
  const finals = new Map();
  for (const p of aa.players || []) {
    const r = calcPlayerStats(p.id, sessions);
    if (r.stats.sessionsPlayed > 0) finals.set(p.id, { src: p, total: r.totalPts });
  }

  const byId = new Map(ss.players.map(p => [p.id, p]));
  let added = 0, changed = 0, same = 0;
  const changes = [];

  for (const [pid, { src, total }] of finals) {
    let dp = byId.get(pid);
    if (!dp) {
      // Carry the player across with every earlier volume they already hold,
      // so the all-time ranking stays complete rather than starting at Vol.6.
      dp = { id: src.id, name: src.name, addedAt: src.addedAt || Date.now(),
             photoUrl: src.photoUrl || "", prevSeriesPts: { ...(src.prevSeriesPts || {}) } };
      ss.players.push(dp); byId.set(pid, dp); added++;
      changes.push(["ADD", src.name, "-", total]);
      continue;
    }
    const before = (dp.prevSeriesPts || {})[SERIES];
    if (before === total) { same++; continue; }
    dp.prevSeriesPts = { ...(dp.prevSeriesPts || {}), [SERIES]: total };
    changed++;
    changes.push(["SET", dp.name, before === undefined ? "-" : before, total]);
  }
  // New arrivals get their Vol.6 total recorded too.
  for (const [pid, { total }] of finals) {
    const dp = byId.get(pid);
    if ((dp.prevSeriesPts || {})[SERIES] === undefined)
      dp.prevSeriesPts = { ...(dp.prevSeriesPts || {}), [SERIES]: total };
  }

  // Every volume Vol.6 knew about, plus Vol.6 itself.
  const names = [...(aa.prevSeriesNames || [])];
  if (!names.includes(SERIES)) names.push(SERIES);
  ss.prevSeriesNames = names;

  const aaPhotos = (await pool.query("select player_id, photo_data from aa_player_photos")).rows;
  const ssHave = new Set((await pool.query("select player_id from ss_player_photos")).rows.map(r => r.player_id));
  const toCopy = aaPhotos.filter(r => finals.has(r.player_id) && !ssHave.has(r.player_id));

  console.log("Vol.6 players with points   :", finals.size);
  console.log("Surge roster before / after :", byId.size - added, "/", byId.size);
  console.log("added / updated / unchanged :", added, "/", changed, "/", same);
  console.log("photos to copy              :", toCopy.length);
  console.log("prevSeriesNames             :", ss.prevSeriesNames.join(", "));
  console.log("\\ntop 10 carried all-time totals:");
  [...finals.values()].sort((a, b) => b.total - a.total).slice(0, 10)
    .forEach((f, i) => console.log("  ", String(i + 1).padStart(2), String(f.src.name).padEnd(22), f.total));

  // A carry-over must never manufacture Vol.7 play.
  if (ss.sessions.length !== sessionsBefore)
    throw new Error("refusing: this script must not touch Vol.7 sessions");

  if (DRY) { console.log("\\nDRY RUN — nothing written."); await pool.end(); return; }

  const newVersion = (ssRow.version || 0) + 1;
  await pool.query("UPDATE ss_tournament_state SET data=$1, version=$2, updated_at=NOW() WHERE id=1",
                   [ss, newVersion]);
  for (const r of toCopy)
    await pool.query(`INSERT INTO ss_player_photos (player_id, photo_data) VALUES ($1,$2)
                      ON CONFLICT (player_id) DO NOTHING`, [r.player_id, r.photo_data]);
  console.log("\\nWROTE ss_tournament_state version", newVersion,
              "| players:", ss.players.length, "| sessions:", ss.sessions.length,
              "| photos copied:", toCopy.length);
  await pool.end();
})().catch(e => { console.error("FAILED:", e.message); process.exit(1); });
'''
    open(OUT, "w").write(js)
    print(f"wrote {os.path.relpath(OUT, ROOT)}  ({len(js)/1024:.0f}KB, engine functions: {len(NEEDED)})")


if __name__ == "__main__":
    main()
