# -*- coding: utf-8 -*-
"""Generate the full-roster merge into a new volume.

`build-carryover.py` carries ONE volume forward, and it only carries players who
played in that volume. That is right for the all-time points of the outgoing
season and wrong for the player database: Blackout opened with 60 names because
60 people played September Surge, while 199 people have played a night since
July and 314 have ever signed up. Everyone else would have had to be re-added by
hand before they could be picked for a session.

This merges EVERY volume's roster instead:

  * a player's base record comes from the latest volume they appear in, so they
    keep the photo and the pre-July volumes (April Clash, Midnight Madness,
    Midnight Rally, June Fury) that only exist as stored prevSeriesPts;
  * on top of that, each volume they actually PLAYED gets its total recomputed
    with that volume's own engine and written into prevSeriesPts.

Recomputing rather than trusting the stored value is deliberate. The Vol.6 ->
Vol.7 carry-over ran while Vol.6 was still in play, so some stored August Attack
totals are provisional; this corrects them.

  python3 ops/build-roster-merge.py blackout
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Oldest first. The order is the order of the series, and the merge relies on it.
SOURCES = [
    dict(key="jh", name="July Heat",       page="july-heat-index.html",       prefix="jh_"),
    dict(key="aa", name="August Attack",   page="august-attack-index.html",   prefix="aa_"),
    dict(key="ss", name="September Surge", page="september-surge-index.html", prefix="ss_"),
]
TARGETS = {
    "blackout": dict(name="Blackout Series", prefix="bo_", api="/opt/blackout-api"),
}

NEEDED = ["getPlayerTeam", "teamWon", "teamGroupResults", "calcGroupStandings",
          "getTopOfGroup", "calcStreak", "koMatchPts", "calcPlayerStats"]


def grab(html, name):
    i = html.index(f"function {name}(")
    j = html.index("{", i)
    depth, k = 0, j
    while True:
        if html[k] == "{":
            depth += 1
        elif html[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    return html[i:k + 1]


def engine_for(src):
    """Each volume's scoring engine, namespaced so three can coexist in one file.

    The volumes do not share an engine — Vol.6 and Vol.7 differ in the group cap
    and the knockout ladder — so running Vol.6's sessions through Vol.7's code
    would quietly produce different totals from the ones attack.urbanpadel.om
    shows. Namespacing keeps each volume scored by its own rules.
    """
    html = open(os.path.join(ROOT, src["page"])).read()
    m = re.search(r"const GROUP_COUNTED_GAMES\s*=\s*\d+;", html)
    if not m:
        sys.exit(f"{src['page']}: GROUP_COUNTED_GAMES not found")
    body = "\n".join([m.group(0)] + [grab(html, n) for n in NEEDED])
    body += f"\nreturn calcPlayerStats;"
    return (f'const calc_{src["key"]} = (function () {{\n'
            f'  const GROUPS = ["A", "B", "C", "D"];\n'
            f'  function getSessionGroups(session) {{ return GROUPS.slice(0, session?.groupCount || 4); }}\n'
            f'{body}\n}})();')


def main():
    if len(sys.argv) != 2 or sys.argv[1] not in TARGETS:
        sys.exit(f"usage: python3 ops/build-roster-merge.py <{'|'.join(TARGETS)}>")
    dst = TARGETS[sys.argv[1]]
    out = os.path.join(HERE, f"sync-roster-to-{sys.argv[1]}.js")

    engines = "\n\n".join(engine_for(s) for s in SOURCES)
    srcs = ",\n  ".join(
        '{ key: "%s", name: "%s", table: "%stournament_state", photos: "%splayer_photos", calc: calc_%s }'
        % (s["key"], s["name"], s["prefix"], s["prefix"], s["key"]) for s in SOURCES)

    js = f'''// GENERATED by ops/build-roster-merge.py — do not edit by hand.
//
// Merges the FULL player database of every past volume into {dst["name"]}.
//
// Blackout opened with 60 players because 60 people played September Surge.
// 199 have played a night since July and 314 have ever signed up; the rest would
// have had to be re-added by hand before they could be picked for a session.
//
// A player's base record comes from the latest volume they appear in, so they
// keep their photo and the pre-July volumes that exist only as stored
// prevSeriesPts. Each volume they actually played then gets its total
// RECOMPUTED with that volume's own engine — the Vol.6 -> Vol.7 carry-over ran
// while Vol.6 was still in play, so some stored August Attack totals are
// provisional, and this corrects them.
//
// Never writes sessions. Idempotent. DRY=1 previews.
// ONLY_PLAYED=1 restricts the merge to people who have actually played a night.
require("dotenv").config({{ path: "{dst['api']}/.env" }});
const {{ Pool }} = require("pg");
const pool = new Pool({{ connectionString: process.env.DATABASE_URL }});
const DRY = process.env.DRY === "1";
const ONLY_PLAYED = process.env.ONLY_PLAYED === "1";

{engines}

const SOURCES = [
  {srcs}
];

(async () => {{
  const toRow = (await pool.query("select data, version from {dst['prefix']}tournament_state where id=1")).rows[0];
  if (!toRow) throw new Error("missing {dst['prefix']}tournament_state — is the {dst['name']} API running?");
  const to = toRow.data && Object.keys(toRow.data).length ? toRow.data : {{}};
  to.players = to.players || [];
  to.sessions = to.sessions || [];
  const sessionsBefore = to.sessions.length;

  // base[id] = the record from the LATEST volume that holds this player
  const base = new Map();
  // totals[id][volumeName] = points, for volumes they actually played
  const totals = new Map();
  const played = new Set();
  const seriesNames = [];

  for (const src of SOURCES) {{
    const st = (await pool.query(`select data from ${{src.table}} where id=1`)).rows[0]?.data;
    if (!st) {{ console.log(`  (no ${{src.table}}, skipping ${{src.name}})`); continue; }}
    for (const n of st.prevSeriesNames || []) if (!seriesNames.includes(n)) seriesNames.push(n);
    if (!seriesNames.includes(src.name)) seriesNames.push(src.name);

    for (const p of st.players || []) base.set(p.id, {{ p, vol: src.name }});
    for (const p of st.players || []) {{
      const r = src.calc(p.id, st.sessions || []);
      if (r.stats.sessionsPlayed > 0) {{
        played.add(p.id);
        if (!totals.has(p.id)) totals.set(p.id, {{}});
        totals.get(p.id)[src.name] = r.totalPts;
      }}
    }}
    console.log(`${{src.name.padEnd(17)}} roster ${{String((st.players || []).length).padStart(4)}}  `
              + `played ${{String([...(st.players || [])].filter(p => src.calc(p.id, st.sessions || []).stats.sessionsPlayed > 0).length).padStart(4)}}`);
  }}

  const byId = new Map(to.players.map(p => [p.id, p]));
  let added = 0, updated = 0, same = 0, skipped = 0;

  for (const [id, {{ p: src }}] of base) {{
    if (ONLY_PLAYED && !played.has(id)) {{ skipped++; continue; }}
    const want = {{ ...(src.prevSeriesPts || {{}}), ...(totals.get(id) || {{}}) }};
    let dp = byId.get(id);
    if (!dp) {{
      dp = {{ id: src.id, name: src.name, addedAt: src.addedAt || Date.now(),
             photoUrl: "", prevSeriesPts: want }};
      to.players.push(dp); byId.set(id, dp); added++;
      continue;
    }}
    const before = JSON.stringify(dp.prevSeriesPts || {{}});
    dp.prevSeriesPts = {{ ...(dp.prevSeriesPts || {{}}), ...want }};
    if (JSON.stringify(dp.prevSeriesPts) === before) same++; else updated++;
  }}

  to.prevSeriesNames = seriesNames;

  // Photos: newest volume that has one wins, and an existing one is never
  // overwritten.
  const have = new Set((await pool.query("select player_id from {dst['prefix']}player_photos")).rows.map(r => r.player_id));
  const toCopy = new Map();
  for (const src of SOURCES) {{
    const rows = (await pool.query(`select player_id, photo_data from ${{src.photos}}`)).rows;
    for (const r of rows) if (byId.has(r.player_id) && !have.has(r.player_id)) toCopy.set(r.player_id, r.photo_data);
  }}

  const allTime = [...byId.values()]
    .map(p => ({{ name: p.name, pts: Object.values(p.prevSeriesPts || {{}}).reduce((a, b) => a + (Number(b) || 0), 0) }}))
    .sort((a, b) => b.pts - a.pts);

  console.log("");
  console.log("roster before / after       :", byId.size - added, "/", byId.size);
  console.log("added / updated / unchanged :", added, "/", updated, "/", same);
  if (ONLY_PLAYED) console.log("skipped (never played)      :", skipped);
  console.log("photos to copy              :", toCopy.size);
  console.log("prevSeriesNames             :", to.prevSeriesNames.join(", "));
  console.log("\\ntop 10 all-time after the merge:");
  allTime.slice(0, 10).forEach((r, i) =>
    console.log("  ", String(i + 1).padStart(2), String(r.name).padEnd(22), r.pts));

  if (to.sessions.length !== sessionsBefore)
    throw new Error("refusing: this script must not touch {dst['name']} sessions");

  if (DRY) {{ console.log("\\nDRY RUN — nothing written."); await pool.end(); return; }}

  const v = (toRow.version || 0) + 1;
  await pool.query("UPDATE {dst['prefix']}tournament_state SET data=$1, version=$2, updated_at=NOW() WHERE id=1",
                   [to, v]);
  for (const [pid, data] of toCopy)
    await pool.query(`INSERT INTO {dst['prefix']}player_photos (player_id, photo_data) VALUES ($1,$2)
                      ON CONFLICT (player_id) DO NOTHING`, [pid, data]);
  console.log("\\nWROTE {dst['prefix']}tournament_state version", v,
              "| players:", to.players.length, "| sessions:", to.sessions.length,
              "| photos copied:", toCopy.size);
  await pool.end();
}})().catch(e => {{ console.error("FAILED:", e.message); process.exit(1); }});
'''
    open(out, "w").write(js)
    print(f"wrote {os.path.relpath(out, ROOT)}  ({len(js)/1024:.0f}KB)")
    print(f"  sources: {', '.join(s['name'] for s in SOURCES)}")
    print(f"  target : {dst['name']} ({dst['prefix']}*)")
    print(f"\n  scp {os.path.relpath(out, ROOT)} urbanpadel:{dst['api']}/")
    print(f"  ssh urbanpadel 'cd {dst['api']} && DRY=1 node {os.path.basename(out)}'")


if __name__ == "__main__":
    main()
