# -*- coding: utf-8 -*-
"""Generate a volume-to-volume carry-over script.

Only the ALL-TIME total crosses volumes. Each player's final points from the
outgoing volume are written into the incoming one as
`prevSeriesPts["<outgoing volume>"]`, which the app sums into the all-time
ranking. The new series table starts at zero and is never written here.

The scoring functions are lifted verbatim out of the OUTGOING volume's own
index.html, so the totals equal what that volume's site shows rather than a
re-implementation that could drift.

This replaces the one-off `build-surge-carryover.py`: the same job has now been
done three times (July Heat -> August Attack -> September Surge -> Blackout), so
it is parametrised rather than copied a fourth time.

  python3 ops/build-carryover.py surge blackout
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Everything a volume needs to be either side of a carry-over.
VOLUMES = {
    "heat":     dict(name="July Heat",       page="july-heat-index.html",       prefix="jh_", api="/opt/july-heat-api"),
    "attack":   dict(name="August Attack",   page="august-attack-index.html",   prefix="aa_", api="/opt/august-attack-api"),
    "surge":    dict(name="September Surge", page="september-surge-index.html", prefix="ss_", api="/opt/september-surge-api"),
    "blackout": dict(name="Blackout Series", page="blackout-index.html",        prefix="bo_", api="/opt/blackout-api"),
}

NEEDED = ["getPlayerTeam", "teamWon", "teamGroupResults", "calcGroupStandings",
          "getTopOfGroup", "calcStreak", "koMatchPts", "calcPlayerStats"]


def grab(html, name):
    i = html.index(f"function {name}(")
    j = html.index("{", i)
    depth, k = 0, j
    while True:
        if html[k] == "{":
            depth += 1
        elif html[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    return html[i:k + 1]


def main():
    if len(sys.argv) != 3 or sys.argv[1] not in VOLUMES or sys.argv[2] not in VOLUMES:
        sys.exit(f"usage: python3 ops/build-carryover.py <from> <to>   "
                 f"(volumes: {', '.join(VOLUMES)})")
    src_key, dst_key = sys.argv[1], sys.argv[2]
    src, dst = VOLUMES[src_key], VOLUMES[dst_key]
    out = os.path.join(HERE, f"sync-{src_key}-to-{dst_key}.js")

    page = os.path.join(ROOT, src["page"])
    if not os.path.exists(page):
        sys.exit(f"missing {src['page']} — the engine is lifted from the OUTGOING volume's page")
    html = open(page).read()
    m = re.search(r"const GROUP_COUNTED_GAMES\s*=\s*\d+;", html)
    if not m:
        sys.exit("GROUP_COUNTED_GAMES not found — has the engine moved?")
    engine = [m.group(0)] + [grab(html, n) for n in NEEDED]

    js = f'''// GENERATED by ops/build-carryover.py — do not edit by hand.
//
// Carries {src['name']} into {dst['name']} as ALL-TIME only: each player's final
// {src['name']} total lands in prevSeriesPts["{src['name']}"], which the app adds
// to the all-time ranking. The new series table starts at zero and is never
// written here — no sessions, no matches, no series points.
//
// The scoring functions below are lifted verbatim from {src['page']}, so totals
// match that volume's own site exactly, including the best-3 group cap, 2x
// sessions, knockout points, streak and comeback bonuses.
//
// Idempotent. Reads {src['prefix']}*, writes only {dst['prefix']}*.
// DRY=1 previews without writing.
require("dotenv").config({{ path: "{dst['api']}/.env" }});
const {{ Pool }} = require("pg");
const pool = new Pool({{ connectionString: process.env.DATABASE_URL }});
const DRY = process.env.DRY === "1";
const SERIES = "{src['name']}";
const GROUPS = ["A", "B", "C", "D"];
function getSessionGroups(session) {{ return GROUPS.slice(0, session?.groupCount || 4); }}

''' + "\n\n".join(engine) + f'''

(async () => {{
  const from = (await pool.query("select data from {src['prefix']}tournament_state where id=1")).rows[0]?.data;
  const toRow = (await pool.query("select data, version from {dst['prefix']}tournament_state where id=1")).rows[0];
  if (!from) throw new Error("missing {src['prefix']}tournament_state");
  if (!toRow) throw new Error("missing {dst['prefix']}tournament_state — is the {dst['name']} API running?");

  const to = toRow.data && Object.keys(toRow.data).length ? toRow.data : {{}};
  to.players = to.players || [];
  to.sessions = to.sessions || [];

  const sessionsBefore = to.sessions.length;
  const sessions = from.sessions || [];
  const unfinished = sessions.filter(s => !s.completed).map(s => s.name || s.date);
  if (unfinished.length)
    console.log("NOTE: " + SERIES + " still has unfinished sessions:", unfinished.join(", "),
                "\\n      totals are provisional — re-run this once they complete.\\n");

  // Final totals, straight from the outgoing volume's own engine.
  const finals = new Map();
  for (const p of from.players || []) {{
    const r = calcPlayerStats(p.id, sessions);
    if (r.stats.sessionsPlayed > 0) finals.set(p.id, {{ src: p, total: r.totalPts }});
  }}

  const byId = new Map(to.players.map(p => [p.id, p]));
  let added = 0, changed = 0, same = 0;

  for (const [pid, {{ src, total }}] of finals) {{
    let dp = byId.get(pid);
    if (!dp) {{
      // Carry the player across with every earlier volume they already hold, so
      // the all-time ranking stays complete rather than starting at this one.
      dp = {{ id: src.id, name: src.name, addedAt: src.addedAt || Date.now(),
             photoUrl: src.photoUrl || "", prevSeriesPts: {{ ...(src.prevSeriesPts || {{}}) }} }};
      to.players.push(dp); byId.set(pid, dp); added++;
    }} else if ((dp.prevSeriesPts || {{}})[SERIES] === total) {{
      same++; continue;
    }} else {{
      changed++;
    }}
    dp.prevSeriesPts = {{ ...(dp.prevSeriesPts || {{}}), [SERIES]: total }};
  }}

  // Every volume the outgoing one knew about, plus itself.
  const names = [...(from.prevSeriesNames || [])];
  if (!names.includes(SERIES)) names.push(SERIES);
  to.prevSeriesNames = names;

  const photos = (await pool.query("select player_id, photo_data from {src['prefix']}player_photos")).rows;
  const have = new Set((await pool.query("select player_id from {dst['prefix']}player_photos")).rows.map(r => r.player_id));
  const toCopy = photos.filter(r => finals.has(r.player_id) && !have.has(r.player_id));

  console.log(SERIES + " players with points :", finals.size);
  console.log("roster before / after       :", byId.size - added, "/", byId.size);
  console.log("added / updated / unchanged :", added, "/", changed, "/", same);
  console.log("photos to copy              :", toCopy.length);
  console.log("prevSeriesNames             :", to.prevSeriesNames.join(", "));
  console.log("\\ntop 10 carried all-time totals:");
  [...finals.values()].sort((a, b) => b.total - a.total).slice(0, 10)
    .forEach((f, i) => console.log("  ", String(i + 1).padStart(2), String(f.src.name).padEnd(22), f.total));

  // A carry-over must never manufacture play in the new volume.
  if (to.sessions.length !== sessionsBefore)
    throw new Error("refusing: this script must not touch {dst['name']} sessions");

  if (DRY) {{ console.log("\\nDRY RUN — nothing written."); await pool.end(); return; }}

  const newVersion = (toRow.version || 0) + 1;
  await pool.query("UPDATE {dst['prefix']}tournament_state SET data=$1, version=$2, updated_at=NOW() WHERE id=1",
                   [to, newVersion]);
  for (const r of toCopy)
    await pool.query(`INSERT INTO {dst['prefix']}player_photos (player_id, photo_data) VALUES ($1,$2)
                      ON CONFLICT (player_id) DO NOTHING`, [r.player_id, r.photo_data]);
  console.log("\\nWROTE {dst['prefix']}tournament_state version", newVersion,
              "| players:", to.players.length, "| sessions:", to.sessions.length,
              "| photos copied:", toCopy.length);
  await pool.end();
}})().catch(e => {{ console.error("FAILED:", e.message); process.exit(1); }});
'''
    open(out, "w").write(js)
    print(f"wrote {os.path.relpath(out, ROOT)}  ({len(js)/1024:.0f}KB)")
    print(f"  {src['name']} ({src['prefix']}*)  ->  {dst['name']} ({dst['prefix']}*)")
    print(f"  engine lifted from {src['page']}: {len(NEEDED)} functions")
    print(f"\n  scp {os.path.relpath(out, ROOT)} urbanpadel:{dst['api']}/")
    print(f"  ssh urbanpadel 'cd {dst['api']} && DRY=1 node {os.path.basename(out)}'")


if __name__ == "__main__":
    main()
