# -*- coding: utf-8 -*-
"""Vendor the brand faces into brand/fonts/ so the renderers never need Google.

Why this exists. Every UPRISING and Blackout card is drawn by headless Chromium
and the display type is Archivo at wdth 125. Chromium in this container does
NOT trust the agent proxy's CA, so a <link> to fonts.googleapis.com fails with
ERR_CERT_AUTHORITY_INVALID — and a failed webfont is not an error, it is a
silent fallback. The whole five-card story series rendered in Times once and
every assertion passed, because they were all about the family that was ASKED
for and none about the glyphs that were drawn.

curl does trust the CA, so the files come down here, once, and get committed.
After that the renderers read file:// and the network is out of the loop.

Latin and latin-ext subsets only — these cards are Latin, and the Cyrillic,
Greek and Vietnamese cuts are four fifths of the bytes.

    python3 ops/vendor-fonts.py          # refresh brand/fonts/
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "brand", "fonts")
os.makedirs(OUT, exist_ok=True)

# Chrome's UA, because Google serves woff2 only to browsers that admit to
# supporting it; with curl's own UA you get truetype, four times the size.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/120.0.0.0 Safari/537.36")
CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=Archivo:ital,wdth,wght@0,62..125,400..900;1,62..125,400..900"
           "&family=JetBrains+Mono:wght@500;700&display=swap")

# The Latin subsets. Google does not name them in the CSS, so they are
# identified by the first range of the unicode-range it ships them with.
LATIN = ("U+0000-00FF", "U+0100-02BA")


def get(url, binary=False):
    r = subprocess.run(["curl", "-sfL", "-A", UA, url],
                       stdout=subprocess.PIPE, check=True)
    return r.stdout if binary else r.stdout.decode()


css = get(CSS_URL)
blocks = re.findall(r"@font-face\s*\{.*?\}", css, re.S)
kept, n = [], 0
for b in blocks:
    rng = re.search(r"unicode-range:\s*([^;,]+)", b)
    if not rng or not rng.group(1).strip().startswith(LATIN):
        continue
    url = re.search(r"url\((https://[^)]+)\)", b).group(1)
    fam = re.search(r"font-family:\s*'([^']+)'", b).group(1)
    ital = "italic" in b
    sub = "latin" if rng.group(1).strip().startswith(LATIN[0]) else "latin-ext"
    name = f"{fam.replace(' ', '')}{'-italic' if ital else ''}-{sub}"
    # Several weights of JetBrains Mono share one subset, so disambiguate.
    w = re.search(r"font-weight:\s*([\d ]+)", b)
    if w and " " not in w.group(1).strip():
        name += "-" + w.group(1).strip()
    name += ".woff2"
    data = get(url, binary=True)
    open(os.path.join(OUT, name), "wb").write(data)
    n += len(data)
    kept.append(b.replace(url, name).replace("url(", "url(./"))
    print(f"  {name}  {len(data) // 1024}KB")

if len(kept) < 4:
    sys.exit(f"only {len(kept)} Latin faces found — the CSS format has changed")

open(os.path.join(OUT, "fonts.css"), "w").write(
    "/* Generated by ops/vendor-fonts.py — do not edit.\n"
    "   Archivo and JetBrains Mono, Latin subsets, SIL Open Font License 1.1.\n"
    "   Local copies so headless Chromium never has to reach the network to\n"
    "   draw a card; a webfont that fails to load is a silent fallback, not an\n"
    "   error. */\n" + "\n".join(kept) + "\n")
print(f"wrote {len(kept)} faces + fonts.css ({n // 1024}KB) to {OUT}")
